In [1]:
import pickle

import numpy as np
import pandas as pd

with open('/home/rui/blacksid/Rui/labeled_data.plkz', 'rb') as f:
    X_train = pickle.load(f, encoding='latin1')
    y_train = pickle.load(f, encoding='latin1')
    X_test = pickle.load(f, encoding='latin1')
    y_test = pickle.load(f, encoding='latin1')

In [3]:
X_train[0]

array([ 3585.        ,  3588.        ,  3588.        ,  3585.        ,
        3586.81298828], dtype=float32)

In [4]:
y_train[0]

array([  2.99731445,  -2.0065918 ,  19.        , -23.        ], dtype=float32)

In [5]:
X_train[1]

array([ 3588.        ,  3589.        ,  3592.        ,  3587.        ,
        3589.81030273], dtype=float32)